/**
 * The curriculum map: ten stages, each made of modules with prerequisites.
 *
 * Stage 1 is fully written. Later stages are listed honestly as "planned":
 * their module titles, intended lessons and unlock rules are real, but the
 * lessons themselves are not written yet and the app says so.
 */
import type { Block, Module, Stage, Text } from './schema';
import { p, t } from './authoring';

function planned(
  id: string,
  stageId: string,
  title: [string, string],
  description: [string, string],
  prerequisites: string[],
  plannedLessons: Array<[string, string]>,
): Module {
  return {
    id,
    stageId,
    title: t(title[0], title[1]),
    description: t(description[0], description[1]),
    prerequisites,
    status: 'planned',
    lessonIds: [],
    plannedLessons: plannedLessons.map(([en, he]) => t(en, he)),
  };
}

/* ------------------------------------------------------------------ */
/* Stage 1 — fully available                                           */
/* ------------------------------------------------------------------ */

const stage1Modules: Module[] = [
  {
    id: 'm1',
    stageId: 's1',
    title: t('How computers think', 'איך מחשבים חושבים'),
    description: t(
      'What a computer actually does, what a program is, how to think in precise steps, and how to read your first error message.',
      'מה מחשב באמת עושה, מהי תוכנית, איך לחשוב בצעדים מדויקים, ואיך לקרוא את הודעת השגיאה הראשונה שלכם.',
    ),
    prerequisites: [],
    status: 'available',
    lessonIds: ['l01-what-computers-do', 'l02-programs-and-files', 'l03-thinking-in-steps', 'l04-first-bug'],
    testId: 'm1-test',
    testOutId: 'm1-test',
  },
  {
    id: 'm2',
    stageId: 's1',
    title: t('Talking to the computer: Python basics', 'לדבר עם המחשב: יסודות פייתון'),
    description: t(
      'Printing, variables, numbers, text, data types, reading input, and formatting output.',
      'הדפסה, משתנים, מספרים, טקסט, טיפוסי נתונים, קליטת קלט ועיצוב פלט.',
    ),
    prerequisites: ['m1'],
    status: 'available',
    lessonIds: ['l05-print-and-strings', 'l06-variables', 'l07-numbers-and-math', 'l08-data-types', 'l09-input', 'l10-fstrings'],
    testId: 'm2-test',
    testOutId: 'm2-test',
  },
  {
    id: 'm3',
    stageId: 's1',
    title: t('Making decisions', 'קבלת החלטות'),
    description: t(
      'Comparisons, True and False, if / elif / else, and combining conditions with and, or, not.',
      'השוואות, True ו-False, if / elif / else, ושילוב תנאים עם and, or, not.',
    ),
    prerequisites: ['m2'],
    status: 'available',
    lessonIds: ['l11-comparisons', 'l12-if-else', 'l13-elif', 'l14-logic'],
    testId: 'm3-test',
    testOutId: 'm3-test',
  },
  {
    id: 'm4',
    stageId: 's1',
    title: t('Repeating things: loops', 'חזרות: לולאות'),
    description: t(
      'while and for loops, counting with range, building totals, nested loops, and a little randomness.',
      'לולאות while ו-for, ספירה עם range, בניית סכומים, לולאות מקוננות וקצת אקראיות.',
    ),
    prerequisites: ['m3'],
    status: 'available',
    lessonIds: ['l15-while', 'l16-for-range', 'l17-accumulators', 'l18-nested-loops', 'l19-random'],
    testId: 'm4-test',
    testOutId: 'm4-test',
    projectIds: ['p-guessing-game'],
  },
  {
    id: 'm5',
    stageId: 's1',
    title: t('Functions: reusable pieces', 'פונקציות: חלקים לשימוש חוזר'),
    description: t(
      'Defining functions, passing information in, getting answers back, and organising a program.',
      'הגדרת פונקציות, העברת מידע פנימה, קבלת תשובות בחזרה, וארגון של תוכנית.',
    ),
    prerequisites: ['m4'],
    status: 'available',
    lessonIds: ['l20-def', 'l21-parameters', 'l22-return', 'l23-scope'],
    testId: 'm5-test',
    testOutId: 'm5-test',
    projectIds: ['p-calculator'],
  },
  {
    id: 'm6',
    stageId: 's1',
    title: t('Collections: lists and dictionaries', 'אוספים: רשימות ומילונים'),
    description: t(
      'Storing many values together, looping over them, and choosing the right structure for the job.',
      'שמירת ערכים רבים יחד, מעבר עליהם בלולאה, ובחירת המבנה הנכון למשימה.',
    ),
    prerequisites: ['m5'],
    status: 'available',
    lessonIds: ['l24-lists', 'l25-list-loops', 'l26-dictionaries', 'l27-nested-data'],
    testId: 'm6-test',
    testOutId: 'm6-test',
    projectIds: ['p-quiz-game'],
  },
  {
    id: 'm7',
    stageId: 's1',
    title: t('When things go wrong: errors', 'כשדברים משתבשים: שגיאות'),
    description: t(
      'Reading tracebacks with confidence, the most common errors, and handling problems with try / except.',
      'קריאת הודעות שגיאה בביטחון, השגיאות הנפוצות ביותר, וטיפול בבעיות עם try / except.',
    ),
    prerequisites: ['m6'],
    status: 'available',
    lessonIds: ['l28-reading-errors', 'l29-try-except'],
    testId: 'm7-test',
    testOutId: 'm7-test',
    projectIds: ['p-text-adventure'],
  },
];

/* ------------------------------------------------------------------ */
/* Stages 2–10 — planned                                               */
/* ------------------------------------------------------------------ */

const stage2Modules: Module[] = [
  planned('m8', 's2', ['Modules, packages and environments', 'מודולים, חבילות וסביבות'],
    ['The standard library, import styles, pip, virtual environments and how a real Python project is laid out.', 'הספרייה הסטנדרטית, צורות import, pip, סביבות וירטואליות ואיך פרויקט פייתון אמיתי בנוי.'],
    ['m7'],
    [['Importing from the standard library', 'ייבוא מהספרייה הסטנדרטית'], ['Writing your own module', 'כתיבת מודול משלכם'], ['Installing packages with pip', 'התקנת חבילות עם pip'], ['Virtual environments', 'סביבות וירטואליות'], ['Project layout and running scripts', 'מבנה פרויקט והרצת סקריפטים']]),
  planned('m9', 's2', ['Files and exceptions in depth', 'קבצים ושגיאות לעומק'],
    ['Reading and writing text files, CSV and JSON, the with statement, and designing your own exceptions.', 'קריאה וכתיבה של קובצי טקסט, CSV ו-JSON, המשפט with, ותכנון חריגות משלכם.'],
    ['m8'],
    [['Reading a file line by line', 'קריאת קובץ שורה אחר שורה'], ['Writing and appending', 'כתיבה והוספה'], ['CSV and JSON', 'CSV ו-JSON'], ['The with statement', 'המשפט with'], ['Raising and designing exceptions', 'זריקת חריגות ותכנונן']]),
  planned('m10', 's2', ['Testing your code', 'בדיקת הקוד שלכם'],
    ['assert, unit tests with pytest, testing habits, and refactoring safely.', 'assert, בדיקות יחידה עם pytest, הרגלי בדיקה, וריפקטורינג בבטחה.'],
    ['m9'],
    [['Why tests exist', 'למה יש בדיקות'], ['Your first pytest test', 'בדיקת pytest ראשונה'], ['Testing edge cases', 'בדיקת מקרי קצה'], ['Refactoring with a safety net', 'ריפקטורינג עם רשת ביטחון']]),
  planned('m11', 's2', ['Object-oriented programming', 'תכנות מונחה עצמים'],
    ['Classes, objects, methods, __init__, inheritance and when objects help (and when they do not).', 'מחלקות, אובייקטים, מתודות, __init__, ירושה ומתי אובייקטים עוזרים (ומתי לא).'],
    ['m10'],
    [['Classes and objects', 'מחלקות ואובייקטים'], ['Methods and self', 'מתודות ו-self'], ['__init__ and attributes', '__init__ ותכונות'], ['Inheritance', 'ירושה'], ['Designing with objects', 'תכנון עם אובייקטים']]),
  planned('m12', 's2', ['Recursion', 'רקורסיה'],
    ['Functions that call themselves: base cases, the call stack, and classic recursive problems.', 'פונקציות שקוראות לעצמן: מקרי בסיס, מחסנית הקריאות ובעיות רקורסיביות קלאסיות.'],
    ['m11'],
    [['A function that calls itself', 'פונקציה שקוראת לעצמה'], ['Base cases and the call stack', 'מקרי בסיס ומחסנית הקריאות'], ['Recursion on lists and trees', 'רקורסיה על רשימות ועצים']]),
  planned('m13', 's2', ['Data structures', 'מבני נתונים'],
    ['Tuples, sets, stacks, queues, linked lists, trees and hash tables, built and used in Python.', 'טאפלים, קבוצות, מחסניות, תורים, רשימות מקושרות, עצים וטבלאות גיבוב, בנויים ומשומשים בפייתון.'],
    ['m12'],
    [['Tuples and sets', 'טאפלים וקבוצות'], ['Stacks and queues', 'מחסניות ותורים'], ['Linked lists', 'רשימות מקושרות'], ['Trees', 'עצים'], ['Hash tables: how dictionaries work', 'טבלאות גיבוב: איך מילונים עובדים']]),
  planned('m14', 's2', ['Algorithms and complexity', 'אלגוריתמים וסיבוכיות'],
    ['Searching, sorting, Big-O notation, and measuring how programs scale.', 'חיפוש, מיון, סימון Big-O, ומדידה של איך תוכניות מתנהגות כשהקלט גדל.'],
    ['m13'],
    [['Linear and binary search', 'חיפוש ליניארי ובינארי'], ['Sorting algorithms', 'אלגוריתמי מיון'], ['Big-O: counting steps', 'Big-O: ספירת צעדים'], ['Measuring real programs', 'מדידת תוכניות אמיתיות']]),
  planned('m15', 's2', ['Git and collaboration', 'Git ועבודה משותפת'],
    ['Version control: commits, branches, merging, GitHub, and working with others.', 'ניהול גרסאות: commits, ענפים, מיזוג, GitHub ועבודה עם אחרים.'],
    ['m8'],
    [['Why version control', 'למה ניהול גרסאות'], ['Commits and history', 'commits והיסטוריה'], ['Branches and merging', 'ענפים ומיזוג'], ['Sharing on GitHub', 'שיתוף ב-GitHub']]),
  planned('m16', 's2', ['APIs, JSON and networking basics', 'ממשקי API, JSON ויסודות רשת'],
    ['How the internet moves data, HTTP requests, JSON, and calling a web API from Python.', 'איך האינטרנט מעביר נתונים, בקשות HTTP, JSON, וקריאה ל-API מפייתון.'],
    ['m9'],
    [['How the web talks: HTTP', 'איך הרשת מדברת: HTTP'], ['JSON in and out', 'JSON פנימה והחוצה'], ['Calling an API with requests', 'קריאה ל-API עם requests'], ['Keys, limits and being polite to servers', 'מפתחות, מגבלות ונימוס כלפי שרתים']]),
  planned('m17', 's2', ['Databases with SQLite', 'מסדי נתונים עם SQLite'],
    ['Tables, rows, queries, and using sqlite3 from Python to store real data.', 'טבלאות, שורות, שאילתות, ושימוש ב-sqlite3 מפייתון כדי לשמור נתונים אמיתיים.'],
    ['m9'],
    [['What a database is', 'מהו מסד נתונים'], ['Tables and rows with sqlite3', 'טבלאות ושורות עם sqlite3'], ['SELECT, INSERT, UPDATE', 'SELECT, INSERT, UPDATE'], ['A small app with persistent data', 'אפליקציה קטנה עם נתונים נשמרים']]),
];

const stage3Modules: Module[] = [
  planned('m18', 's3', ['Text-based programs', 'תוכניות מבוססות טקסט'],
    ['Bigger console programs: menus, simulations, a to-do manager and a text adventure with saved games.', 'תוכניות קונסול גדולות יותר: תפריטים, סימולציות, מנהל משימות והרפתקת טקסט עם שמירת משחק.'],
    ['m7'],
    [['Menus and program state', 'תפריטים ומצב תוכנית'], ['A simulation step by step', 'סימולציה צעד אחר צעד'], ['Saving and loading', 'שמירה וטעינה'], ['Project: text adventure with rooms and items', 'פרויקט: הרפתקת טקסט עם חדרים וחפצים']]),
  planned('m19', 's3', ['Game loops, coordinates and movement', 'לולאות משחק, קואורדינטות ותנועה'],
    ['The game loop, frames, x/y coordinates, moving things, keyboard input and drawing in a browser canvas.', 'לולאת המשחק, פריימים, קואורדינטות x/y, הזזת דברים, קלט מקלדת וציור בקנבס בדפדפן.'],
    ['m18'],
    [['The game loop', 'לולאת המשחק'], ['Coordinates and movement', 'קואורדינטות ותנועה'], ['Keyboard input', 'קלט מקלדת'], ['Collisions and scoring', 'התנגשויות וניקוד'], ['Game state: start, playing, game over', 'מצב משחק: התחלה, משחק, סיום']]),
  planned('m20', 's3', ['2D games with Pygame', 'משחקי דו-ממד עם Pygame'],
    ['Sprites, images, sound, levels and a complete 2D game on your own computer.', 'ספרייטים, תמונות, צליל, שלבים ומשחק דו-ממדי שלם במחשב שלכם.'],
    ['m19', 'm11'],
    [['Setting up Pygame locally', 'התקנת Pygame מקומית'], ['Sprites and images', 'ספרייטים ותמונות'], ['Sound and levels', 'צליל ושלבים'], ['Project: a complete arcade game', 'פרויקט: משחק ארקייד שלם']]),
];

const stage4Modules: Module[] = [
  planned('m21', 's4', ['What transfers between languages', 'מה עובר בין שפות'],
    ['Variables, loops, functions and data structures look different but mean the same. What changes: syntax, types, tooling, runtime.', 'משתנים, לולאות, פונקציות ומבני נתונים נראים אחרת אבל אומרים אותו דבר. מה משתנה: תחביר, טיפוסים, כלים, סביבת ריצה.'],
    ['m14'],
    [['The same program in four languages', 'אותה תוכנית בארבע שפות'], ['Static vs dynamic typing', 'טיפוסים סטטיים לעומת דינמיים'], ['Compiled vs interpreted', 'מהודר לעומת מפורש']]),
  planned('m22', 's4', ['JavaScript and TypeScript for the web', 'JavaScript ו-TypeScript לרשת'],
    ['HTML, CSS, the DOM, events, and TypeScript types, ending with an interactive web page.', 'HTML, CSS, ה-DOM, אירועים וטיפוסי TypeScript, עד דף אינטרנט אינטראקטיבי.'],
    ['m21'],
    [['HTML and CSS basics', 'יסודות HTML ו-CSS'], ['JavaScript: Python ideas, new syntax', 'JavaScript: רעיונות מפייתון, תחביר חדש'], ['The DOM and events', 'ה-DOM ואירועים'], ['TypeScript types', 'טיפוסים ב-TypeScript'], ['Project: an interactive page', 'פרויקט: דף אינטראקטיבי']]),
  planned('m23', 's4', ['SQL for databases', 'SQL למסדי נתונים'],
    ['Deeper SQL: joins, aggregation, indexes and designing tables well.', 'SQL לעומק: joins, אגרגציה, אינדקסים ותכנון טבלאות נכון.'],
    ['m17', 'm21'],
    [['Joins', 'Joins'], ['Grouping and aggregation', 'קיבוץ ואגרגציה'], ['Indexes and performance', 'אינדקסים וביצועים'], ['Designing tables', 'תכנון טבלאות']]),
  planned('m24', 's4', ['C# for Unity', 'C# עבור Unity'],
    ['C# syntax and types, classes, and how Unity scripts attach behaviour to game objects.', 'תחביר וטיפוסים ב-C#, מחלקות, ואיך סקריפטים ב-Unity מצמידים התנהגות לאובייקטי משחק.'],
    ['m21', 'm11'],
    [['C# basics for Python programmers', 'יסודות C# למתכנתי פייתון'], ['Classes and interfaces', 'מחלקות וממשקים'], ['Your first Unity script', 'הסקריפט הראשון ב-Unity']]),
  planned('m25', 's4', ['C++ for systems and Unreal', 'C++ למערכות ו-Unreal'],
    ['Memory, pointers, compilation, and the C++ needed for performance work and Unreal Engine.', 'זיכרון, מצביעים, הידור, וה-C++ הנחוץ לעבודת ביצועים ול-Unreal Engine.'],
    ['m21', 'm13'],
    [['Compiling your first C++ program', 'הידור תוכנית C++ ראשונה'], ['Memory and pointers', 'זיכרון ומצביעים'], ['Classes and the standard library', 'מחלקות והספרייה הסטנדרטית'], ['A look at Unreal', 'הצצה ל-Unreal']]),
];

const stage5Modules: Module[] = [
  planned('m26', 's5', ['Algebra and functions for programmers', 'אלגברה ופונקציות למתכנתים'],
    ['Linear functions, slopes, exponents and logarithms, always with code and pictures.', 'פונקציות ליניאריות, שיפועים, חזקות ולוגריתמים, תמיד עם קוד ותמונות.'],
    ['m7'],
    [['Functions as machines', 'פונקציות כמכונות'], ['Lines and slopes', 'קווים ושיפועים'], ['Exponents and logarithms', 'חזקות ולוגריתמים']]),
  planned('m27', 's5', ['Vectors and matrices', 'וקטורים ומטריצות'],
    ['Vectors as arrows and as lists, dot products, matrices as transformations, and NumPy.', 'וקטורים כחיצים וכרשימות, מכפלה סקלרית, מטריצות כטרנספורמציות, ו-NumPy.'],
    ['m26'],
    [['Vectors: arrows and lists', 'וקטורים: חיצים ורשימות'], ['Dot product and length', 'מכפלה סקלרית ואורך'], ['Matrices as transformations', 'מטריצות כטרנספורמציות'], ['NumPy essentials', 'יסודות NumPy']]),
  planned('m28', 's5', ['Probability and statistics', 'הסתברות וסטטיסטיקה'],
    ['Chance, distributions, mean and variance, sampling, and why randomness matters for AI.', 'סיכוי, התפלגויות, ממוצע ושונות, דגימה, ולמה אקראיות חשובה לבינה מלאכותית.'],
    ['m26'],
    [['Probability with simulations', 'הסתברות עם סימולציות'], ['Distributions', 'התפלגויות'], ['Mean, variance and sampling', 'ממוצע, שונות ודגימה'], ['Bayes in one page', 'בייס בעמוד אחד']]),
  planned('m29', 's5', ['Derivatives, gradients and optimisation', 'נגזרות, גרדיאנטים ואופטימיזציה'],
    ['Slopes of curves, gradients of surfaces, and gradient descent as a search for the lowest point.', 'שיפועים של עקומות, גרדיאנטים של משטחים, וירידת גרדיאנט כחיפוש אחרי הנקודה הנמוכה ביותר.'],
    ['m27'],
    [['Slope of a curve', 'שיפוע של עקומה'], ['Gradients', 'גרדיאנטים'], ['Gradient descent step by step', 'ירידת גרדיאנט צעד אחר צעד'], ['Learning rate and convergence', 'קצב למידה והתכנסות']]),
  planned('m30', 's5', ['Working with data', 'עבודה עם נתונים'],
    ['Datasets, cleaning, splitting into train / validation / test, and the trap of data leakage.', 'מערכי נתונים, ניקוי, חלוקה לאימון / אימות / בדיקה, והמלכודת של דליפת נתונים.'],
    ['m28'],
    [['Loading and cleaning data', 'טעינה וניקוי נתונים'], ['Train, validation and test splits', 'חלוקה לאימון, אימות ובדיקה'], ['Data leakage', 'דליפת נתונים']]),
  planned('m31', 's5', ['Machine learning basics', 'יסודות למידת מכונה'],
    ['Supervised and unsupervised learning, evaluation metrics, overfitting and generalisation.', 'למידה מונחית ולא מונחית, מדדי הערכה, התאמת-יתר והכללה.'],
    ['m29', 'm30'],
    [['What learning from data means', 'מה פירוש ללמוד מנתונים'], ['Linear regression from scratch', 'רגרסיה ליניארית מאפס'], ['Classification and metrics', 'סיווג ומדדים'], ['Clustering', 'אשכולות'], ['Overfitting and generalisation', 'התאמת-יתר והכללה']]),
];

const stage6Modules: Module[] = [
  planned('m32', 's6', ['A single neuron', 'נוירון בודד'],
    ['Weights, bias, activation, and training one neuron with gradient descent.', 'משקלים, הטיה, אקטיבציה, ואימון נוירון אחד עם ירידת גרדיאנט.'],
    ['m31'],
    [['The neuron as a tiny function', 'הנוירון כפונקציה זעירה'], ['Activation functions', 'פונקציות אקטיבציה'], ['Training one neuron', 'אימון נוירון אחד']]),
  planned('m33', 's6', ['Networks from scratch', 'רשתות מאפס'],
    ['Layers, losses, backpropagation, and a small network written in plain Python and NumPy.', 'שכבות, פונקציות הפסד, back-propagation, ורשת קטנה שנכתבת בפייתון ו-NumPy בלבד.'],
    ['m32'],
    [['Layers and forward pass', 'שכבות ומעבר קדימה'], ['Loss functions', 'פונקציות הפסד'], ['Backpropagation', 'Backpropagation'], ['Project: a network from scratch', 'פרויקט: רשת מאפס']]),
  planned('m34', 's6', ['Training in practice', 'אימון בפועל'],
    ['Optimisers, batches, epochs, learning-rate schedules, and reading training curves.', 'אופטימייזרים, batches, epochs, לוחות זמנים לקצב למידה, וקריאת עקומות אימון.'],
    ['m33'],
    [['Optimisers', 'אופטימייזרים'], ['Batches and epochs', 'Batches ו-epochs'], ['Reading training curves', 'קריאת עקומות אימון']]),
  planned('m35', 's6', ['PyTorch', 'PyTorch'],
    ['Tensors, autograd, nn.Module, DataLoader and training a real model on your computer.', 'טנזורים, autograd, nn.Module, DataLoader ואימון מודל אמיתי במחשב שלכם.'],
    ['m34'],
    [['Tensors and autograd', 'טנזורים ו-autograd'], ['Building models with nn.Module', 'בניית מודלים עם nn.Module'], ['Data loading and training loops', 'טעינת נתונים ולולאות אימון'], ['Saving and loading models', 'שמירה וטעינה של מודלים']]),
  planned('m36', 's6', ['Embeddings and representation', 'הטמעות (embeddings) וייצוג'],
    ['Turning words, items and images into vectors, and why nearby vectors mean similar things.', 'הפיכת מילים, פריטים ותמונות לווקטורים, ולמה וקטורים קרובים משמעם דברים דומים.'],
    ['m35'],
    [['What an embedding is', 'מהי הטמעה'], ['Similarity and nearest neighbours', 'דמיון ושכנים קרובים'], ['Visualising embeddings', 'הדמיה של הטמעות']]),
];

const stage7Modules: Module[] = [
  planned('m37', 's7', ['Tokens and next-token prediction', 'טוקנים וחיזוי הטוקן הבא'],
    ['Tokenisation, vocabularies, and the surprisingly simple objective behind language models.', 'טוקניזציה, אוצר מילים, והמטרה הפשוטה להפתיע שמאחורי מודלי שפה.'],
    ['m36'],
    [['Tokenisation', 'טוקניזציה'], ['A bigram model in 30 lines', 'מודל ביגרם ב-30 שורות'], ['Sampling and temperature', 'דגימה וטמפרטורה']]),
  planned('m38', 's7', ['Attention and transformers', 'קשב (attention) וטרנספורמרים'],
    ['Attention as weighted lookup, positional information, and the transformer block.', 'קשב כחיפוש משוקלל, מידע על מיקום, ובלוק הטרנספורמר.'],
    ['m37'],
    [['Attention as weighted lookup', 'קשב כחיפוש משוקלל'], ['Positional information', 'מידע על מיקום'], ['The transformer block', 'בלוק הטרנספורמר'], ['Inference and generation', 'הסקה ויצירה']]),
  planned('m39', 's7', ['Training a tiny language model', 'אימון מודל שפה זעיר'],
    ['Train a small character-level model on a small text corpus, watch it improve, and understand its limits.', 'אמנו מודל קטן ברמת תווים על קורפוס טקסט קטן, צפו בו משתפר, והבינו את מגבלותיו.'],
    ['m38'],
    [['Preparing a corpus', 'הכנת קורפוס'], ['Training loop and checkpoints', 'לולאת אימון ונקודות שמירה'], ['Evaluating and sampling', 'הערכה ודגימה']]),
  planned('m40', 's7', ['Using pretrained models', 'שימוש במודלים מאומנים מראש'],
    ['Prompting, tool use, retrieval-augmented generation, fine-tuning and parameter-efficient fine-tuning — and what each one actually changes.', 'פרומפטים, שימוש בכלים, יצירה מוגברת-אחזור (RAG), כוונון עדין וכוונון עדין יעיל בפרמטרים — ומה כל אחד מהם באמת משנה.'],
    ['m39'],
    [['Prompting and tool use', 'פרומפטים ושימוש בכלים'], ['Retrieval-augmented generation', 'יצירה מוגברת-אחזור (RAG)'], ['Fine-tuning vs. conversation memory', 'כוונון עדין לעומת זיכרון שיחה'], ['Parameter-efficient fine-tuning (LoRA)', 'כוונון עדין יעיל בפרמטרים (LoRA)']]),
  planned('m41', 's7', ['Hardware, cost and realism', 'חומרה, עלות ומציאות'],
    ['Memory, GPUs, time, datasets and money: what is practical on a laptop, what needs a cloud GPU, and what only labs can do.', 'זיכרון, מעבדים גרפיים, זמן, מערכי נתונים וכסף: מה מעשי במחשב נייד, מה דורש GPU בענן, ומה רק מעבדות יכולות לעשות.'],
    ['m40'],
    [['Estimating memory and time', 'הערכת זיכרון וזמן'], ['Local, cloud and paid APIs', 'מקומי, ענן וממשקי API בתשלום'], ['Why nobody trains GPT-scale models at home', 'למה אף אחד לא מאמן מודלים בגודל GPT בבית']]),
];

const stage8Modules: Module[] = [
  planned('m42', 's8', ['Environments, rewards and episodes', 'סביבות, תגמולים ואפיזודות'],
    ['Observations, actions, rewards, episodes, policies and value functions, on a tiny grid world.', 'תצפיות, פעולות, תגמולים, אפיזודות, מדיניות ופונקציות ערך, על עולם-רשת זעיר.'],
    ['m31'],
    [['The agent loop', 'לולאת הסוכן'], ['Rewards and returns', 'תגמולים ותשואות'], ['Policies and value functions', 'מדיניות ופונקציות ערך'], ['Exploration vs exploitation', 'חקירה לעומת ניצול']]),
  planned('m43', 's8', ['Tabular Q-learning', 'Q-learning טבלאי'],
    ['Learn a Q-table on grid worlds, tune exploration, and evaluate honestly.', 'למדו טבלת Q על עולמות-רשת, כוונו חקירה, והעריכו ביושר.'],
    ['m42'],
    [['The Q-table', 'טבלת ה-Q'], ['The update rule', 'כלל העדכון'], ['Evaluation and baselines', 'הערכה וקווי בסיס'], ['Project: escape the maze', 'פרויקט: לברוח מהמבוך']]),
  planned('m44', 's8', ['Deep reinforcement learning: DQN and PPO', 'למידת חיזוק עמוקה: DQN ו-PPO'],
    ['Replacing the table with a network, replay buffers, DQN, policy gradients and PPO.', 'החלפת הטבלה ברשת, מאגרי חזרה, DQN, גרדיאנטים של מדיניות ו-PPO.'],
    ['m43', 'm35'],
    [['From tables to networks', 'מטבלאות לרשתות'], ['DQN', 'DQN'], ['Policy gradients and PPO', 'גרדיאנטים של מדיניות ו-PPO'], ['Stability tricks', 'טריקים ליציבות']]),
  planned('m45', 's8', ['Imitation learning and evolutionary methods', 'למידה בחיקוי ושיטות אבולוציוניות'],
    ['Learning from demonstrations, and searching for good policies without gradients at all.', 'למידה מהדגמות, וחיפוש מדיניות טובה בלי גרדיאנטים בכלל.'],
    ['m43'],
    [['Behaviour cloning', 'שיבוט התנהגות'], ['Evolution strategies', 'אסטרטגיות אבולוציוניות'], ['When to use which approach', 'מתי להשתמש באיזו גישה']]),
];

const stage9Modules: Module[] = [
  planned('m46', 's9', ['Building an environment interface', 'בניית ממשק סביבה'],
    ['reset, step, observations, valid actions, rewards, done signals, time limits and reproducible seeds — on a game you wrote.', 'reset, step, תצפיות, פעולות חוקיות, תגמולים, אותות סיום, מגבלות זמן וזרעים (seeds) ניתנים לשחזור — על משחק שכתבתם.'],
    ['m43', 'm19'],
    [['Reset and step', 'Reset ו-step'], ['Designing observations and actions', 'תכנון תצפיות ופעולות'], ['Rewards and done signals', 'תגמולים ואותות סיום'], ['Time limits and seeds', 'מגבלות זמן וזרעים']]),
  planned('m47', 's9', ['Training, evaluation and checkpoints', 'אימון, הערכה ונקודות שמירה'],
    ['Separating training from evaluation, saving and loading agents, watching them play, and comparing against random and scripted baselines.', 'הפרדה בין אימון להערכה, שמירה וטעינה של סוכנים, צפייה במשחק שלהם, והשוואה לקווי בסיס אקראיים ומתוסרטים.'],
    ['m46'],
    [['Training vs evaluation', 'אימון לעומת הערכה'], ['Checkpoints', 'נקודות שמירה'], ['Watching the agent play', 'צפייה בסוכן משחק'], ['Baselines: random and scripted', 'קווי בסיס: אקראי ומתוסרט'], ['Reward hacking and poor generalisation', 'ניצול תגמולים והכללה חלשה']]),
  planned('m48', 's9', ['Projects: navigation and objectives', 'פרויקטים: ניווט ומטרות'],
    ['Agents that learn to navigate, avoid obstacles, collect items and reach goals in games you build.', 'סוכנים שלומדים לנווט, להימנע ממכשולים, לאסוף פריטים ולהגיע ליעדים במשחקים שאתם בונים.'],
    ['m47'],
    [['Project: learn to navigate', 'פרויקט: ללמוד לנווט'], ['Project: obstacle avoidance', 'פרויקט: הימנעות ממכשולים'], ['Project: a game objective', 'פרויקט: מטרת משחק']]),
  planned('m49', 's9', ['LLM-controlled characters', 'דמויות בשליטת מודל שפה'],
    ['Letting a language model choose structured actions or call tools inside a game, and why that is not the same as training.', 'לתת למודל שפה לבחור פעולות מובנות או לקרוא לכלים בתוך משחק, ולמה זה לא אותו דבר כמו אימון.'],
    ['m47', 'm40'],
    [['Structured actions and tools', 'פעולות מובנות וכלים'], ['An LLM playing through an API is not being trained', 'מודל שפה שמשחק דרך API לא מתאמן'], ['Comparing LLM agents with RL agents', 'השוואת סוכני LLM לסוכני RL']]),
];

const stage10Modules: Module[] = [
  planned('m50', 's10', ['3D foundations', 'יסודות תלת-ממד'],
    ['3D coordinates, vectors, transforms, cameras and the Godot 4 engine as the primary path (Unity and Unreal as alternatives).', 'קואורדינטות תלת-ממד, וקטורים, טרנספורמציות, מצלמות ומנוע Godot 4 כמסלול הראשי (Unity ו-Unreal כחלופות).'],
    ['m27', 'm20', 'm47'],
    [['3D coordinates and vectors', 'קואורדינטות ווקטורים בתלת-ממד'], ['Transforms and cameras', 'טרנספורמציות ומצלמות'], ['Meshes, materials and lighting', 'רשתות פוליגונים, חומרים ותאורה'], ['Physics, collisions and animation', 'פיזיקה, התנגשויות ואנימציה']]),
  planned('m51', 's10', ['Performance and simulation speed', 'ביצועים ומהירות סימולציה'],
    ['Frame rate vs training steps, headless simulation, parallel environments and profiling.', 'קצב פריימים לעומת צעדי אימון, סימולציה ללא תצוגה, סביבות מקביליות ופרופיילינג.'],
    ['m50'],
    [['Frame rate vs training steps', 'קצב פריימים לעומת צעדי אימון'], ['Headless and parallel environments', 'סביבות ללא תצוגה ומקביליות'], ['Profiling a game', 'פרופיילינג של משחק']]),
  planned('m52', 's10', ['Capstone: a 3D world with a learning agent', 'פרויקט גמר: עולם תלת-ממד עם סוכן לומד'],
    ['Build a 3D environment, connect an agent, train it, evaluate it, and display its behaviour.', 'בנו סביבת תלת-ממד, חברו סוכן, אמנו אותו, העריכו אותו והציגו את התנהגותו.'],
    ['m51', 'm44'],
    [['Designing the environment', 'תכנון הסביבה'], ['Connecting and training the agent', 'חיבור ואימון הסוכן'], ['Evaluation and presentation', 'הערכה והצגה']]),
];

export const modules: Module[] = [
  ...stage1Modules,
  ...stage2Modules,
  ...stage3Modules,
  ...stage4Modules,
  ...stage5Modules,
  ...stage6Modules,
  ...stage7Modules,
  ...stage8Modules,
  ...stage9Modules,
  ...stage10Modules,
];

/* ------------------------------------------------------------------ */
/* Stages                                                              */
/* ------------------------------------------------------------------ */

function stage(
  id: string,
  number: number,
  title: [string, string],
  summary: [string, string],
  description: Block[],
  status: Stage['status'],
  moduleIds: string[],
  unlockNote: [string, string],
  compute: Stage['compute'],
): Stage {
  return {
    id,
    number,
    title: t(title[0], title[1]),
    summary: t(summary[0], summary[1]),
    description,
    status,
    moduleIds,
    unlockNote: t(unlockNote[0], unlockNote[1]),
    compute,
  };
}

export const stages: Stage[] = [
  stage('s1', 1, ['Computer and programming foundations', 'יסודות המחשב והתכנות'],
    ['From "what is a computer" to writing real Python programs with decisions, loops, functions and collections.', 'מ"מה זה מחשב" ועד כתיבת תוכניות פייתון אמיתיות עם החלטות, לולאות, פונקציות ואוספים.'],
    [p('This stage assumes nothing. It starts with how a computer follows instructions and ends with you writing programs that make decisions, repeat work, and organise data. Every lesson runs in the browser.', 'השלב הזה לא מניח שום ידע קודם. הוא מתחיל באיך מחשב מבצע הוראות ומסתיים בכך שאתם כותבים תוכניות שמקבלות החלטות, חוזרות על עבודה ומארגנות נתונים. כל שיעור רץ בדפדפן.')],
    'available', ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7'],
    ['Open to everyone. Take the placement assessment to skip modules you already know.', 'פתוח לכולם. עברו את מבחן המיקום כדי לדלג על מודולים שאתם כבר מכירים.'],
    'browser'),
  stage('s2', 2, ['Practical Python and computer science', 'פייתון מעשי ומדעי המחשב'],
    ['Modules, files, testing, object-oriented programming, recursion, data structures, algorithms, Git, APIs and databases.', 'מודולים, קבצים, בדיקות, תכנות מונחה עצמים, רקורסיה, מבני נתונים, אלגוריתמים, Git, ממשקי API ומסדי נתונים.'],
    [p('Here you learn to work like a programmer: organise code into modules, test it, use version control, and understand the data structures and algorithms behind everything else. Some modules need Python installed on your computer.', 'כאן לומדים לעבוד כמו מתכנתים: לארגן קוד במודולים, לבדוק אותו, להשתמש בניהול גרסאות, ולהבין את מבני הנתונים והאלגוריתמים שמאחורי כל השאר. חלק מהמודולים דורשים פייתון מותקן במחשב.')],
    'planned', ['m8', 'm9', 'm10', 'm11', 'm12', 'm13', 'm14', 'm15', 'm16', 'm17'],
    ['Unlocks after finishing Stage 1 (or testing out of all its modules).', 'נפתח אחרי סיום שלב 1 (או מעבר מבחני דילוג על כל המודולים שלו).'],
    'local'),
  stage('s3', 3, ['Small programs and 2D games', 'תוכניות קטנות ומשחקי דו-ממד'],
    ['Calculators, quizzes, text adventures, simulations, and progressively more complex 2D games.', 'מחשבונים, חידונים, הרפתקאות טקסט, סימולציות ומשחקי דו-ממד מורכבים יותר ויותר.'],
    [p('Game loops, input, coordinates, movement, collisions, scoring and game state — first in the browser, then with Pygame on your computer.', 'לולאות משחק, קלט, קואורדינטות, תנועה, התנגשויות, ניקוד ומצב משחק — קודם בדפדפן, ואחר כך עם Pygame במחשב שלכם.')],
    'planned', ['m18', 'm19', 'm20'],
    ['Unlocks after Stage 1; the Pygame module also needs the object-oriented programming module of Stage 2.', 'נפתח אחרי שלב 1; המודול של Pygame דורש גם את מודול התכנות מונחה העצמים משלב 2.'],
    'local'),
  stage('s4', 4, ['Other programming languages', 'שפות תכנות נוספות'],
    ['JavaScript/TypeScript for the web, SQL for data, C# for Unity and C++ for systems and Unreal.', 'JavaScript/TypeScript לרשת, SQL לנתונים, C# ל-Unity ו-C++ למערכות ול-Unreal.'],
    [p('Purposeful language tracks. Each one starts by explaining what transfers from Python and what changes, so you learn a second language much faster than the first.', 'מסלולי שפה מכווני מטרה. כל אחד מתחיל בהסבר מה עובר מפייתון ומה משתנה, כך שתלמדו שפה שנייה הרבה יותר מהר מהראשונה.')],
    'planned', ['m21', 'm22', 'm23', 'm24', 'm25'],
    ['Unlocks after the algorithms module of Stage 2.', 'נפתח אחרי מודול האלגוריתמים של שלב 2.'],
    'local'),
  stage('s5', 5, ['Mathematics, data and machine learning', 'מתמטיקה, נתונים ולמידת מכונה'],
    ['Algebra, vectors, matrices, probability, statistics, derivatives, gradients, optimisation, datasets and classic machine learning.', 'אלגברה, וקטורים, מטריצות, הסתברות, סטטיסטיקה, נגזרות, גרדיאנטים, אופטימיזציה, מערכי נתונים ולמידת מכונה קלאסית.'],
    [p('The mathematics is taught gradually, through visual examples and code, always next to the project that needs it.', 'המתמטיקה נלמדת בהדרגה, דרך דוגמאות חזותיות וקוד, תמיד ליד הפרויקט שזקוק לה.')],
    'planned', ['m26', 'm27', 'm28', 'm29', 'm30', 'm31'],
    ['Unlocks after Stage 1. The machine learning module also needs the data module.', 'נפתח אחרי שלב 1. מודול למידת המכונה דורש גם את מודול הנתונים.'],
    'local'),
  stage('s6', 6, ['Neural networks and deep learning', 'רשתות נוירונים ולמידה עמוקה'],
    ['From a single neuron to networks, backpropagation, optimisers and PyTorch.', 'מנוירון בודד לרשתות, back-propagation, אופטימייזרים ו-PyTorch.'],
    [p('You build a small network from scratch before touching a framework, so nothing in PyTorch feels like magic.', 'אתם בונים רשת קטנה מאפס לפני שנוגעים בספרייה, כך ששום דבר ב-PyTorch לא ירגיש כמו קסם.')],
    'planned', ['m32', 'm33', 'm34', 'm35', 'm36'],
    ['Unlocks after the machine learning module of Stage 5.', 'נפתח אחרי מודול למידת המכונה של שלב 5.'],
    'local'),
  stage('s7', 7, ['Language models and LLMs', 'מודלי שפה ו-LLM'],
    ['Tokens, embeddings, attention, transformers, tiny models you train yourself, and honest guidance on cost and hardware.', 'טוקנים, הטמעות, קשב, טרנספורמרים, מודלים זעירים שאתם מאמנים בעצמכם, והדרכה כנה על עלות וחומרה.'],
    [p('You train a tiny educational language model and explore pretrained ones, and you learn to tell apart training from scratch, fine-tuning, retrieval, prompting and tool use.', 'אתם מאמנים מודל שפה חינוכי זעיר וחוקרים מודלים מאומנים מראש, ולומדים להבדיל בין אימון מאפס, כוונון עדין, אחזור, פרומפטים ושימוש בכלים.')],
    'planned', ['m37', 'm38', 'm39', 'm40', 'm41'],
    ['Unlocks after the embeddings module of Stage 6.', 'נפתח אחרי מודול ההטמעות של שלב 6.'],
    'cloud'),
  stage('s8', 8, ['AI agents and reinforcement learning', 'סוכני בינה מלאכותית ולמידת חיזוק'],
    ['Observations, actions, rewards, policies, Q-learning, DQN, PPO, imitation learning and evolutionary methods.', 'תצפיות, פעולות, תגמולים, מדיניות, Q-learning, DQN, PPO, למידה בחיקוי ושיטות אבולוציוניות.'],
    [p('Simple environments first, tabular methods second, deep methods only once the neural network prerequisites are met.', 'קודם סביבות פשוטות, אחר כך שיטות טבלאיות, ושיטות עמוקות רק אחרי שמתקיימים תנאי הקדם של רשתות נוירונים.')],
    'planned', ['m42', 'm43', 'm44', 'm45'],
    ['Unlocks after the machine learning module of Stage 5; deep RL also needs PyTorch from Stage 6.', 'נפתח אחרי מודול למידת המכונה של שלב 5; למידת חיזוק עמוקה דורשת גם PyTorch משלב 6.'],
    'local'),
  stage('s9', 9, ['Connecting AI to games', 'חיבור בינה מלאכותית למשחקים'],
    ['Build a game that exposes an environment interface, train an agent in it, evaluate it, and compare with baselines.', 'בנו משחק שחושף ממשק סביבה, אמנו בו סוכן, העריכו אותו והשוו לקווי בסיס.'],
    [p('Reset, observe, act, step, reward, done, seeds, time limits, checkpoints, evaluation and baselines — implemented, not just described. Plus LLM-controlled characters and why an LLM playing via an API is not being trained.', 'Reset, תצפית, פעולה, step, תגמול, סיום, זרעים, מגבלות זמן, נקודות שמירה, הערכה וקווי בסיס — ממומשים, לא רק מתוארים. וגם דמויות בשליטת מודל שפה, ולמה מודל שפה שמשחק דרך API לא מתאמן.')],
    'planned', ['m46', 'm47', 'm48', 'm49'],
    ['Unlocks after tabular Q-learning (Stage 8) and the game-loop module (Stage 3).', 'נפתח אחרי Q-learning טבלאי (שלב 8) ומודול לולאת המשחק (שלב 3).'],
    'local'),
  stage('s10', 10, ['Advanced 3D games and AI', 'משחקי תלת-ממד מתקדמים ובינה מלאכותית'],
    ['3D maths, engines, physics, animation, performance, and a capstone: a 3D world with a trained agent.', 'מתמטיקה של תלת-ממד, מנועים, פיזיקה, אנימציה, ביצועים ופרויקט גמר: עולם תלת-ממד עם סוכן מאומן.'],
    [p('Locked until you have substantial programming, mathematics, game development and AI experience — or demonstrate it. Godot 4 is the primary engine for a coherent path; Unity (ML-Agents) and Unreal are offered as alternatives afterwards.', 'נעול עד שיש לכם ניסיון ממשי בתכנות, מתמטיקה, פיתוח משחקים ובינה מלאכותית — או עד שתוכיחו אותו. Godot 4 הוא המנוע הראשי למסלול קוהרנטי; Unity (ML-Agents) ו-Unreal מוצעים כחלופות אחר כך.')],
    'planned', ['m50', 'm51', 'm52'],
    ['Unlocks after vectors and matrices (Stage 5), 2D games with Pygame (Stage 3) and training & evaluation (Stage 9).', 'נפתח אחרי וקטורים ומטריצות (שלב 5), משחקי דו-ממד עם Pygame (שלב 3) ואימון והערכה (שלב 9).'],
    'local'),
];

export const stageTitleShort: Record<string, Text> = Object.fromEntries(stages.map((s) => [s.id, s.title]));
